-- Seed Ontario Farm Shows for 2026
INSERT INTO public.events (slug, title, description, short_description, start_date, end_date, start_time, end_time, venue_name, address_line1, city, region, latitude, longitude, event_type, venue_type, is_free, adult_price, child_price, price_notes, website_url, organizer_name, features, status, is_featured, recurring_pattern) VALUES

('chatham-kent-farm-show', 'Chatham-Kent Farm Show', 'A regional farm show with 130+ exhibitors showcasing farm equipment, communications, and technology across 35,000+ sq ft of show space. Includes a speaker series on modern agricultural practices and innovations.', 'Regional farm show with 130+ exhibitors showcasing equipment and agricultural technology.', '2026-01-28', '2026-01-29', '09:00', '17:00', 'John D. Bradley Centre', '565 Richmond St', 'Chatham', 'western', 42.4048, -82.1910, 'farm_show', 'indoor', false, 10.00, 0.00, 'Ages 16 and under free. $2 from each ticket donated to AgScape.', 'https://chathamkentfarmshow.com/', 'Chatham-Kent Farm Show Committee', ARRAY['parking', 'food_vendors', 'demonstrations'], 'published', false, 'annual'),

('ontario-fruit-vegetable-convention', 'Ontario Fruit and Vegetable Convention', 'Ontario''s premier horticultural event with 161 exhibitors, 10 session halls, and speakers covering fruit and vegetable growing. Includes a Farmers and Friends Reception and networking events.', 'Premier horticultural event with 161 exhibitors covering fruit and vegetable production.', '2026-02-18', '2026-02-19', '08:00', '17:00', 'Niagara Falls Convention Centre', NULL, 'Niagara Falls', 'southern', 43.1060, -79.0716, 'crop_show', 'indoor', false, NULL, NULL, 'Registration required. Contact glenna@ofvc.ca for pricing.', 'https://www.ofvc.ca/', 'OFVC', ARRAY['parking', 'food_vendors', 'demonstrations'], 'published', false, 'annual'),

('london-farm-show', 'London Farm Show', 'The largest spring indoor farm show in eastern Canada, featuring 330+ exhibitors across 230,000 sq ft. Showcases the latest agricultural technology and equipment with free shuttle service between buildings.', 'Largest spring indoor farm show in eastern Canada with 330+ exhibitors.', '2026-03-04', '2026-03-06', '09:00', '17:00', 'Western Fair District', '845 Florence St', 'London', 'western', 42.9849, -81.2453, 'farm_show', 'indoor', false, NULL, 0.00, 'Advance online tickets save 25%. Children 12 and under free. Free parking.', 'https://www.londonfarmshow.com/', 'London Farm Show', ARRAY['parking', 'food_vendors', 'demonstrations', 'kids_activities'], 'published', true, 'annual'),

('ottawa-valley-farm-show', 'Ottawa Valley Farm Show', 'Ontario''s longest-running agricultural expo and the largest ag trade show in Ontario east of Toronto. Over 13,000 visitors and 360 exhibitors showcasing the latest in farming innovation. Running since 1959.', 'Longest-running agricultural expo in Ontario with 360 exhibitors since 1959.', '2026-03-10', '2026-03-12', '09:00', '17:00', 'EY Centre', '4899 Uplands Drive', 'Ottawa', 'eastern', 45.3235, -75.6692, 'farm_show', 'indoor', false, 15.00, 0.00, '$12 advance online / $15 at gate. Children 12 and under free. Free parking.', 'https://www.ottawafarmshow.com/', 'Ottawa Valley Seed Growers Association', ARRAY['parking', 'food_vendors', 'demonstrations', 'kids_activities'], 'published', true, 'annual'),

('gfo-march-classic', 'GFO March Classic', 'Grain Farmers of Ontario''s annual conference with 800+ attendees and 70 exhibitors. Theme: Breaking New Ground: Embracing Change. Features keynote speakers, panel discussions, and an evening banquet with entertainment.', 'Grain farmers conference with 800+ attendees and 70 exhibitors.', '2026-03-24', '2026-03-24', '08:00', '21:00', 'Niagara Falls Convention Centre', '6815 Stanley Ave', 'Niagara Falls', 'southern', 43.1060, -79.0716, 'conference', 'indoor', false, NULL, NULL, 'Registration required. Early bird draw for those who register before February 28.', 'https://gfo.ca/march-classic/', 'Grain Farmers of Ontario', ARRAY['food_vendors', 'demonstrations'], 'published', false, 'annual'),

('ontario-swine-conference', 'Ontario Swine Conference', 'Combines the former London Swine Conference and Ontario Pork''s AGM. Two days of science-backed insights on economics, innovation, trends, and trade in the Ontario swine sector.', 'Swine industry conference with science-backed insights on innovation and trade.', '2026-03-24', '2026-03-25', '08:30', '17:00', 'DoubleTree by Hilton', NULL, 'London', 'western', 42.9849, -81.2453, 'conference', 'indoor', false, NULL, NULL, 'Registration required. Check website for pricing.', 'https://ontarioswineconference.ca/', 'Ontario Pork', ARRAY['food_vendors', 'demonstrations'], 'published', false, 'annual'),

('canadian-dairy-xpo', 'Canadian Dairy XPO', 'Canada''s largest dairy industry showcase with over 300 international exhibiting companies and 17,000+ professional attendees. 82% of visitors are active dairy farmers. Features the latest in genetics, robotics, nutrition, and milking technology.', 'Canada''s largest dairy showcase with 300+ exhibitors and 17,000+ attendees.', '2026-04-01', '2026-04-02', '09:00', '17:00', 'Rotary Complex', '353 McCarthy Rd', 'Stratford', 'southwestern', 43.3700, -80.9823, 'dairy_expo', 'indoor', false, 25.00, NULL, NULL, 'https://canadiandairyxpo.ca/', 'DLG Markets North America', ARRAY['parking', 'food_vendors', 'demonstrations', 'livestock'], 'published', true, 'annual'),

('farm-food-care-conference', 'Farm & Food Care Ontario Conference', 'Annual conference themed Farming in Focus: Real Stories, Real Impact. Features speakers on agricultural storytelling and building public trust, including keynote by Tyler Heppell.', 'Annual conference on agricultural storytelling and building public trust.', '2026-04-09', '2026-04-09', '09:00', '16:00', 'GrandWay Events Centre', NULL, 'Elora', 'southwestern', 43.6804, -80.4317, 'conference', 'indoor', false, NULL, NULL, 'Registration required. Check website for pricing.', 'https://www.farmfoodcareon.org/conference2026/', 'Farm & Food Care Ontario', ARRAY['food_vendors'], 'published', false, 'annual'),

('ontario-pork-congress', 'Ontario Pork Congress', 'Celebrates community, history, and the hog industry''s future. Industry leaders and exhibitors showcase products and services. Includes the Ontario Pork Industry Council Hog Jog fundraiser.', 'Annual celebration of the hog industry with exhibitors and community events.', '2026-06-17', '2026-06-18', '09:00', '17:00', 'Stratford Rotary Complex', '353 McCarthy Rd', 'Stratford', 'southwestern', 43.3700, -80.9823, 'livestock_show', 'mixed', false, NULL, NULL, 'Contact admin@porkcongress.on.ca for pricing.', 'https://www.porkcongress.on.ca/', 'Ontario Pork Industry Council', ARRAY['parking', 'food_vendors', 'demonstrations', 'livestock', 'competitions'], 'published', false, 'annual'),

('canadian-national-exhibition', 'Canadian National Exhibition (CNE)', 'Canada''s largest community event and one of the top 10 agricultural fairs in North America. Features agricultural displays, carnival midway, live entertainment, food, and more. Attracts 1.5 million+ visitors annually since 1879.', 'Canada''s largest community event with agricultural displays, midway, and entertainment.', '2026-08-21', '2026-09-07', '10:00', '22:00', 'Exhibition Place', NULL, 'Toronto', 'gta', 43.6340, -79.4171, 'agricultural_fair', 'mixed', false, 27.00, 22.00, 'Family pass ~$84. Children 4 and under free. Look for Kid''s Toonie Mondays ($2 kids admission).', 'https://www.theex.com/', 'CNE Association', ARRAY['parking', 'food_vendors', 'kids_activities', 'accessible', 'livestock', 'demonstrations', 'competitions', 'entertainment', 'midway'], 'published', true, 'annual'),

('canadas-outdoor-farm-show', 'Canada''s Outdoor Farm Show', 'Eastern Canada''s largest outdoor agriculture expo spanning 100+ acres. Over 700 exhibitors and 40,000+ visitors across three days. Features live field demonstrations of farm machinery, working crop plots, drone demos, and educational seminars.', 'Eastern Canada''s largest outdoor agriculture expo with 700+ exhibitors on 100+ acres.', '2026-09-15', '2026-09-17', '08:30', '17:00', 'Discovery Farm Woodstock', '744906 Oxford Road 17', 'Woodstock', 'southwestern', 43.1306, -80.7468, 'equipment_expo', 'outdoor', false, 25.00, 10.00, 'Children 12 and under free.', 'https://www.outdoorfarmshow.com/', 'Glacier FarmMedia LP', ARRAY['parking', 'food_vendors', 'demonstrations', 'kids_activities', 'competitions'], 'published', true, 'annual'),

('international-plowing-match', 'International Plowing Match & Rural Expo', 'North America''s largest outdoor agricultural and rural expo. Expected to attract 200,000+ visitors over five days. Features plowing competitions, live demonstrations, educational exhibits, and a celebration of rural Ontario life. 50th anniversary edition.', 'North America''s largest outdoor agricultural expo with plowing competitions.', '2026-09-22', '2026-09-26', '08:00', '17:00', 'Lang Farms', NULL, 'Walkerton', 'southwestern', 44.1275, -81.1443, 'agricultural_fair', 'outdoor', false, NULL, NULL, 'Pricing not yet announced. Check website.', 'https://www.plowingmatch.org/event/2026-international-plowing-match-rural-expo/', 'Ontario Plowmen''s Association', ARRAY['parking', 'food_vendors', 'demonstrations', 'kids_activities', 'competitions', 'entertainment', 'livestock'], 'published', true, 'annual'),

('carp-fair', 'Carp Fair', 'Known as The Best Little Fair in Canada. A four-day celebration of rural life featuring agricultural exhibits, midway, antique displays, strongman competitions, petting zoo, live music, and Ag Tent educational programming. Running since 1863.', 'Known as The Best Little Fair in Canada with agricultural exhibits and family fun.', '2026-09-24', '2026-09-27', '09:00', '22:00', 'Carp Agricultural Fairgrounds', '3790 Carp Road', 'Carp', 'eastern', 45.3511, -76.0476, 'agricultural_fair', 'mixed', false, 18.00, 8.00, 'Under 6 free. Free parking at 3629 Carp Road with free shuttle.', 'https://www.carpfair.ca/', 'Carp Agricultural Society', ARRAY['parking', 'food_vendors', 'kids_activities', 'livestock', 'demonstrations', 'competitions', 'entertainment', 'midway'], 'published', false, 'annual'),

('lindsay-central-exhibition', 'Lindsay Central Exhibition', 'A major multi-day fair featuring livestock shows, midway rides, bouncy castles, circus performers, arts and crafts, and agricultural exhibits. The 4th largest agricultural fair in Ontario, running since 1854.', '4th largest agricultural fair in Ontario with livestock shows and family entertainment.', '2026-09-18', '2026-09-20', '09:00', '22:00', 'Lindsay Exhibition Fairgrounds', '354 Angeline St S', 'Lindsay', 'central', 44.3491, -78.7428, 'agricultural_fair', 'mixed', false, NULL, NULL, 'Check website for pricing.', 'https://lindsayex.com/', 'Lindsay Agricultural Society', ARRAY['parking', 'food_vendors', 'kids_activities', 'livestock', 'competitions', 'entertainment', 'midway'], 'published', false, 'annual'),

('markham-fair', 'Markham Fair', 'One of Canada''s oldest and largest country fairs since 1844. Features midway rides, live music, comfort food, agricultural displays, tractor pulls, demolition derby, Monster Truck shows, horse pulls, and livestock exhibits. 700+ volunteers, 3,000 exhibitors, 70,000+ visitors.', 'One of Canada''s oldest country fairs with 3,000 exhibitors and 70,000+ visitors.', '2026-10-01', '2026-10-04', '09:00', '22:00', 'Markham Fairgrounds', NULL, 'Markham', 'gta', 43.8761, -79.2633, 'agricultural_fair', 'mixed', false, 25.00, 10.00, 'Most attractions included with gate admission.', 'https://www.markhamfair.ca/', 'Markham Fair Board', ARRAY['parking', 'food_vendors', 'kids_activities', 'livestock', 'demonstrations', 'competitions', 'entertainment', 'midway'], 'published', true, 'annual'),

('norfolk-county-fair', 'Norfolk County Fair & Horse Show', 'Ontario''s oldest agricultural fair since 1840. A 7-day Thanksgiving tradition and one of Ontario''s largest fairs. Canada''s largest outdoor horse show with 15,000+ competition entries. Features equine events, livestock, artisan exhibits, and major concerts. 115,000+ annual visitors.', 'Ontario''s oldest agricultural fair and Canada''s largest outdoor horse show.', '2026-10-06', '2026-10-12', '09:00', '22:00', 'Norfolk County Fairgrounds', '172 South Drive', 'Simcoe', 'southern', 42.8380, -80.3040, 'agricultural_fair', 'mixed', false, 15.00, 0.00, '$13 advance / $15 at gate. Weekly pass ~$60. Kids 12 and under free.', 'https://www.norfolkagsociety.com/', 'Norfolk Agricultural Society', ARRAY['parking', 'food_vendors', 'kids_activities', 'livestock', 'demonstrations', 'competitions', 'entertainment', 'midway'], 'published', false, 'annual'),

('rockton-worlds-fair', 'Rockton World''s Fair', 'A 4-day Thanksgiving weekend tradition featuring the Huge Heavy Horse Show, 8 Horse Hitch Tent, large 4-H shows, livestock shows, Ag-Alive educational tent, championship demolition derby, and ongoing entertainment. Running since 1852.', 'Thanksgiving weekend tradition with heavy horse shows and championship demolition derby.', '2026-10-09', '2026-10-12', '09:00', '22:00', 'Rockton Fairgrounds', '812 Old Highway 8', 'Rockton', 'southwestern', 43.2217, -80.2808, 'agricultural_fair', 'mixed', false, NULL, NULL, 'Check website for pricing.', 'https://rocktonworldsfair.com/', 'Rockton Agricultural Society', ARRAY['parking', 'food_vendors', 'kids_activities', 'livestock', 'demonstrations', 'competitions', 'entertainment', 'midway'], 'published', false, 'annual'),

('royal-agricultural-winter-fair', 'Royal Agricultural Winter Fair', 'The world''s largest combined indoor agricultural fair and international equestrian competition. Over 6,000 animals including 4,900+ head of livestock and 900+ horses. Nine food competitions and 320,000+ visits. A crown jewel of Canadian agriculture since 1922.', 'World''s largest indoor agricultural fair and international equestrian competition.', '2026-11-06', '2026-11-15', '09:00', '21:00', 'Exhibition Place', '100 Princes'' Blvd', 'Toronto', 'gta', 43.6340, -79.4171, 'livestock_show', 'indoor', false, NULL, NULL, 'GO Transit combo pass available. Access 2 card provides free support person admission.', 'https://www.royalfair.org/', 'Royal Agricultural Winter Fair', ARRAY['parking', 'food_vendors', 'kids_activities', 'accessible', 'livestock', 'demonstrations', 'competitions', 'entertainment'], 'published', true, 'annual'),

('breakfast-on-the-farm', 'Breakfast on the Farm', 'Visitors enjoy a farm-fresh breakfast and get behind-the-scenes tours of working Ontario farms. Kids and adults can meet farm animals, explore equipment, play interactive games, and chat with local farmers. A unique opportunity for non-farming Ontarians to connect with agriculture.', 'Farm-fresh breakfast and behind-the-scenes tours of working Ontario farms.', '2026-07-11', '2026-07-11', '09:00', '13:00', 'Rotating Host Farm', NULL, 'Various Locations', 'southwestern', 42.8360, -80.3060, 'other', 'outdoor', false, NULL, NULL, 'Ticketed event. Check website or Eventbrite for tickets.', 'https://www.farmfoodcareon.org/', 'Farm & Food Care Ontario', ARRAY['food_vendors', 'kids_activities', 'livestock', 'demonstrations'], 'published', false, 'annual'),

('fergus-fall-fair', 'Fergus Fall Fair', 'One of Ontario''s oldest community agricultural fairs since 1836. The 10th oldest fair in Ontario, showcasing local agriculture with livestock competitions, homecraft displays, and family entertainment in Wellington County.', 'One of Ontario''s oldest agricultural fairs since 1836 in Wellington County.', '2026-09-11', '2026-09-13', '09:00', '22:00', 'Fergus Fairgrounds', NULL, 'Fergus', 'southwestern', 43.8687, -80.3742, 'agricultural_fair', 'mixed', false, NULL, NULL, 'Check website for pricing.', 'https://fergusfallfair.ca/', 'Fergus Agricultural Society', ARRAY['parking', 'food_vendors', 'kids_activities', 'livestock', 'competitions', 'entertainment'], 'published', false, 'annual');
