import { z } from "zod";

export const eventSchema = z.object({
  title: z.string().min(1, "Title is required").max(200),
  description: z.string().optional().nullable(),
  short_description: z.string().max(160).optional().nullable(),
  start_date: z.string().min(1, "Start date is required"),
  end_date: z.string().optional().nullable(),
  start_time: z.string().optional().nullable(),
  end_time: z.string().optional().nullable(),
  venue_name: z.string().optional().nullable(),
  address_line1: z.string().optional().nullable(),
  address_line2: z.string().optional().nullable(),
  city: z.string().min(1, "City is required"),
  region: z.string().min(1, "Region is required"),
  postal_code: z.string().optional().nullable(),
  latitude: z.number().min(-90).max(90),
  longitude: z.number().min(-180).max(180),
  event_type: z.string().min(1, "Event type is required"),
  venue_type: z.string().min(1, "Venue type is required"),
  is_free: z.boolean().default(false),
  adult_price: z.number().positive().optional().nullable(),
  child_price: z.number().positive().optional().nullable(),
  price_notes: z.string().optional().nullable(),
  image_url: z.string().url().optional().nullable(),
  thumbnail_url: z.string().url().optional().nullable(),
  floor_plan_url: z.string().url().optional().nullable(),
  website_url: z.string().url().optional().nullable(),
  ticket_url: z.string().url().optional().nullable(),
  organizer_name: z.string().optional().nullable(),
  organizer_email: z.string().email().optional().nullable(),
  organizer_phone: z.string().optional().nullable(),
  features: z.array(z.string()).optional().nullable(),
  meta_title: z.string().max(70).optional().nullable(),
  meta_description: z.string().max(160).optional().nullable(),
  status: z.enum(["draft", "published", "cancelled", "archived"]).default("draft"),
  is_featured: z.boolean().default(false),
  recurring_pattern: z.string().optional().nullable(),
});

export type EventFormData = z.infer<typeof eventSchema>;
